<?php $this->layout('theme-default::base.phtml', ['title' => 'User Profile']); ?>

<!--
Make a welcome block:

$this->start('block name')
// block content.
$this->stop()
-->
<?php $this->start('welcome') ?>
    <h1>Welcome!</h1>
    <p>Hello <?php echo $this->e($title); ?></p>
<?php $this->stop() ?>

<!--
Default content block.
-->
<p>Hello, <?php echo $this->e($id); ?></p>
<p>Hello, <?php echo $this->e($title); ?></p>
<p>Hello, <?php echo $this->e($content); ?></p>
