{% extends 'base.phtml' %}

{% block title %}Welcome!{% endblock %}

{% block head %}
    {{ parent() }}
    <style type="text/css">
        .important { color: #336699; }
    </style>
{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
    <p class="important">Welcome to my awesome homepage.</p>
    <p>{{ id }}</p>
    <p>{{ title }}</p>
    <p>{{ content }}</p>
{% endblock %}

{% block footer %}
    <p>&copy; Copyright 2015 by <a href="http://domain.invalid/">you</a></p>
{% endblock %}
