<?php $this->layout('theme-default::base.phtml', ['title' => $title]); ?>

<!--
Make a welcome block:

$this->start('block name')
// block content.
$this->stop()
-->
<?php $this->start('welcome') ?>
    <h1>Welcome!</h1>
    <p>Hello <?php echo $title; ?></p>
<?php $this->stop() ?>

<!--
Default content block.
-->
<p><?php echo $articleId; ?></p>
<p><?php echo $title; ?></p>
<?php echo $content; ?>
